baseurl = "/"
languageCode = "en-us"
title = "Teun van Veggel"
description = 'Freelance Drupal specialist'
theme = "type"
disqusShortname = "nuezio"
googleAnalytics = "UA-107417893-1"
paginate = 10


[params]
	author = "Teun van Veggel"
	description = "I am a **freelance Drupal specialist** with over 8 years of experience building websites and web applications."
	keywords = "drupal, web development"
	copyright = "Teun van Veggel"
	[params.social]
		# Insert your accout name and the icon will be shown in the right menu
		rss = true
		homepage = false
		email = "teun@nuezweb.com"
		behance = ""
		bitbucket  =""
		dribbble = ""
		facebook = ""
		flickr = ""
		github = "nuez"
		googleplus = ""
		instagram = ""
		linkedin = "teunvanveggel"
		pinterest = ""
		reddit = ""
		soundcloud = ""
		stackexchange = ""
		steam = ""
		tumblr = ""
		twitter = "nuezweb"
		wordpress = ""
		youtube = ""
		gitlab = ""
		trello = ""
